-- LOGICAL OPERATORS-AND,OR,NOT
-- USING LOGICAL AND OPERATOR
SELECT * FROM employee3
WHERE salary>=50000 AND age>=30;

--USING LOGICAL OR OPEARTOR
SELECT * FROM employee3
WHERE salary>=50000 OR age>=30;

--USING LOGICAL NOT OPERATOR

SELECT * FROM employee3
WHERE NOT(department='IT');
